POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkvDpMOkcmlqw6QiLCJpZCI6IjY1OTQxYmY0ZDg0N2U0YTM0NWU0YmI1MSIsImlhdCI6MTcwNDIxMDI3MH0.sRmgjSpi7_QK09DUMjuGxJxxODRsQ2-JvGMIXf7JArs

{
    "title": "Cocktailpalat illanistujaisiin ja muuhun 2",
    "author": "Hellapoliisi 2",
    "url": "https://www.hellapoliisi.fi/reseptit/pikkusuolaiset/cocktailpalat-illanistujaisiin/",
    "likes": 2,
    "userId": "6593da472a5b0793e27b94fe"
}
