POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Cocktailpalat illanistujaisiin 2",
    "author": "Hellapoliisi 2",
    "url": "https://www.hellapoliisi.fi/reseptit/pikkusuolaiset/cocktailpalat-illanistujaisiin/",
    "likes": 2,
    "userId": "6593da472a5b0793e27b94fe"
}